import clr
import cMode
from datetime import datetime

clr.AddReference("RoboArmCalculations")
from RoboArmCalculations import RACalc

obj = RACalc()

print(obj.calcDistance(0,0,2,0))
print(cMode.calcDistance((0,0),(2,0)))
print()
print(obj.calcDistance(0,0,1,1))
print(cMode.calcDistance((0,0),(1,1)))
print()
print(obj.calcDistance(0,0,10,64))
print(cMode.calcDistance((0,0),(10,64)))
print()
print(obj.calcDistance(15,2,0,0))
print(cMode.calcDistance((15,2),(0,0)))
print()


print(obj.calculateJointAngles(5,10))
print(cMode.getJointAngles(5,10))
print()
print(obj.calculateJointAngles(5,0))
print(cMode.getJointAngles(5,0))
print()
print(obj.calculateJointAngles(5,11))
print(cMode.getJointAngles(5,11))
print()
print(obj.calculateJointAngles(5,-1))
print(cMode.getJointAngles(5,-1))
print()
print(obj.calculateJointAngles(5,7))
print(cMode.getJointAngles(5,7))
print()
print(obj.calculateJointAngles(5,8))
print(cMode.getJointAngles(5,8))
print()
print(obj.calculateJointAngles(5,9))
print(cMode.getJointAngles(5,9))
print()
print(obj.calculateJointAngles(5,3))
print(cMode.getJointAngles(5,3))
print()
print(obj.calculateJointAngles(5,2))
print(cMode.getJointAngles(5,2))
print()
print(obj.calculateJointAngles(5,1))
print(cMode.getJointAngles(5,1))
print()
print(obj.calculateJointAngles(5,6.3))
print(cMode.getJointAngles(5,6.3))
print()
print(obj.calculateJointAngles(5,9.2))
print(cMode.getJointAngles(5,9.2))
print()
print(obj.calculateJointAngles(5,3.8))
print(cMode.getJointAngles(5,3.8))
print()
